### ISSUE TITLE
Delete datetime from template ?

### ISSUE THREAD

**Issue by zmstone** [tsloughter/grpcbox_plugin#12]
Can we delete datetime from the templates?
https://github.com/tsloughter/grpcbox_plugin/blob/v0.8.0/priv/grpcbox_service_bhvr.erl#L6
https://github.com/tsloughter/grpcbox_plugin/blob/v0.8.0/priv/grpcbox_service_client.erl#L6

If I understand correctly, the `Force` parameter passed to rebar is hard coded to `true`:
https://github.com/tsloughter/grpcbox_plugin/blob/v0.8.0/src/grpcbox_plugin_prv.erl#L141
This means modules are always re-generated with different content.
Not sure if we have used this plugin in the wrong way though.

**Comment by tsloughter** [comment]
Sorry, should have responded to this years ago! Answer is yes, but it may need to be an option, I'm checking #18 now.
