### ISSUE TITLE
Inapposite include code in xxx_client.erl created by rebar3 grpc gen 

### ISSUE THREAD

**Issue by minghu6** [tsloughter/grpcbox_plugin#2]
Now when I use rebar3 grpc gen to create XXX_client.erl. 
The file includes grpcbox.hrl,  `-include("grpcbox.hrl").`

However, rebar3 compile can't find the hrl file

```sh
===> Verifying dependencies...
===> Compiling epy_mind
===> Compiling src/helloworld_greeter_client.erl failed
src/helloworld_greeter_client.erl:13: can't find include file "grpcbox.hrl"

src/helloworld_greeter_client.erl:32: record grpcbox_def undefined
```
Maybe should use `-include_lib("grpcbox/include/grpcbox.hrl").` ?

**Comment by tsloughter** [comment]
Ah, yup, fixing.

**Comment by minghu6** [comment]
I have found the new commit fixed it.
