### ISSUE TITLE
v0.8.0 - service_bhvr.erl and service_client.erl files are not generated

### ISSUE THREAD

**Issue by craftgoldman** [tsloughter/grpcbox_plugin#9]
In existing project using grpcbox and grpcbox_plugin noticed that recently when applying rebar3 grpc gen command, the following error message appeared:
Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.

Also, the following error was produced:
===> Error building 
<project>/_build/default/lib/<project>/ebin/<project>_pb.bea#
        none: error writing file: no such file or directory

And service_bhvr.erl and service_client.erl files are NOT generated at all.

After reverting back to version v0.7.0 of grpcbox_plugin - everything is Ok.

Erlang OTP 22. rebar3 version is 3.13.2 - compiling under Windows 10 Pro from powershell.

**Comment by maksimryndin** [comment]
@craftgoldman Hello! I wonder if you tried different options?
```
{grpc, [{protos, "src/protos"},     %% path to protofiles (relative to your_app directory)
        {out_dir, "src"},    %% path to outputdir for clients and behaviours  (relative to your_app directory)
        {type, "all"},    %% type of generated (all|client)
        {gpb_opts, [{module_name_suffix, "_pb"}]}
]}.
```
For me version v0.8.0 of plugin and **master branch** of grpcbox works. Please let me know if it helps.

**Comment by vasu-dasari** [comment]
@maksimryndin `grpcbox_plugin` 0.8.0 did not work me either. But, 0.7.0 works for me. I even tried your grpc options, still no luck. So, going back to 0.7.0

**Comment by maksimryndin** [comment]
@vasu-dasari I've ended up with the following
`{plugins, [{grpcbox_plugin, 
           {git, "git://github.com/maksimryndin/grpcbox_plugin.git", 
           {branch, "bugfix-pb_module_name"}}}
           ]}.`

So I use master branch with minor bugfix for the case when  pb module name has to be surrounded by single quotes to  become proper atom.

pr https://github.com/tsloughter/grpcbox_plugin/pull/11

**Comment by vasu-dasari** [comment]
Thanks @maksimryndin. Will try this out over the weekend.

**Comment by russagit** [comment]
> @vasu-dasari I've ended up with the following
> `{plugins, [{grpcbox_plugin, {git, "git://github.com/maksimryndin/grpcbox_plugin.git", {branch, "bugfix-pb_module_name"}}} ]}.`
> 
> So I use master branch with minor bugfix for the case when pb module name has to be surrounded by single quotes to become proper atom.
> 
> pr #11

This fix helped me, thanks

**Comment by fenollp** [comment]
I can reproduce this (although for me no error is produced).
I tried all `grpcbox_plugin` versions mentioned so far, on OTP 22 and 23, with latest rebar3 (3.15.1).
Excerpt from my rebar.config:
```erlang
{grpc, [{protos, "../copain/proto/"}
        %% https://hexdocs.pm/gpb/gpb_compile.html
       ,{gpb_opts, [{module_name_suffix, "_pb"}
                   ,strings_as_binaries
                   ,type_specs
                   ,{verify, always}
                   ]}
       ]}.

{plugins, [rebar3_fmt
          ,grpcbox_plugin
          ]}.

{deps, [grpcbox
       ,...
       ]}.
```
I invoke with `rebar3 do grpc gen -t all --force, fmt`.

Note: deleting `src/<package>_<service>_client.erl` and running the command does not even re-create the file.

**Comment by fenollp** [comment]
Turns out in here https://github.com/tsloughter/grpcbox_plugin/blob/v0.8.0/src/grpcbox_plugin_prv.erl#L161-L164
paths point to non-existing files e.g.:
```erlang
ProtoBeam = "/home/pete/Documents/_cake/jungle.git/cake/src/tst_pb.beam"
ModulePath = "/home/pete/Documents/_cake/jungle.git/cake/src/fm_u_client.erl"
```
and `fun filelib:last_modified/1` on that returns `0` which filters out these per https://github.com/tsloughter/grpcbox_plugin/blob/v0.8.0/src/grpcbox_plugin_prv.erl#L204-L205

**Comment by tsloughter** [comment]
Ooh, why are beam files in the `src` dir! Is that the real issue that #16 was just a quick fix for?

**Comment by fenollp** [comment]
Yes that PR was a quick fix for this issue. 
Hmm note that I do not have any beam file in my src but it is looking for some beam files in that dir.
